import React, { createContext, useContext, useEffect, useState } from 'react';

// Simple translation dictionary (can be expanded)
const translations = {
  en: {
    appName: 'HealthConnect',
    icu: 'ICU',
    generalBed: 'General Bed',
    cabin: 'Cabin',

    hospitals: 'Hospitals',
    doctors: 'Doctors',
    appointments: 'Appointments',
    ambulance: 'Ambulance',
    locations: 'Locations',
    booking: 'Booking',
    contact: 'Contact',
    link: 'Link',
    dashboard: 'Dashboard',
    signIn: 'Sign in',
    register: 'Register',
    findHospitals: 'Find Hospitals',
    findDoctor: 'Find a Doctor',
    latestReviews: 'Latest reviews',
    newsletterTitle: 'Follow the latest trends',
    newsletterSubtitle: 'With our daily newsletter',
    newsletterPlaceholder: 'you@example.com',
    submit: 'Submit',
    logout: 'Logout',
    loading: 'Loading...',
    accessDenied: 'Access denied',
    // Auth / common
    email: 'Email',
    password: 'Password',
    login: 'Log In',
    verification: 'Verification',
    dontHaveAccount: "Don't have an account?",
    haveAccount: 'Already have an account?',
    forgotPassword: 'Forgot password?',
    backToLogin: 'Back to Login',
    otpSentTo: 'We sent a code to',
    enterCode: 'Enter 6-digit Code',
    processing: 'Processing...',
    verifyCode: 'Verify Code',
    registration: 'Registration',
    name: 'Name',
    gender: 'Gender',
    dateOfBirth: 'Date of Birth',
    registerAs: 'Registered as',
    patient: 'Patient',
    doctor: 'Doctor',
    admin: 'Admin',
    acceptTerms: 'I accept the terms',
    myProfile: 'My Profile',
    myDocuments: 'My Documents',
    myAppointments: 'My Appointments',
    adminDashboard: 'Admin Dashboard',
    manageAvailability: 'Manage My Availability',
    saveChanges: 'Save Changes',
    save: 'Save',
    upload: 'Upload',
    book: 'Book',
    reschedule: 'Reschedule',
    cancel: 'Cancel',
    noRecordsFound: 'No medical records found',
    myMedicalRecords: 'My Medical Records',
    // Search / details
    loadingHospitals: 'Loading hospitals...',
    loadingDoctors: 'Loading doctors...',
    noHospitals: 'No hospitals found',
    noDoctors: 'No doctors found',
    noDoctorsFound: 'No doctors found',
    consultationLabel: 'Consultation',
    visitingFeeLabel: 'Visiting Fee',
    visitingFee: 'Visiting Fee',
    taka: 'taka',
    instructionHospital:
      'Please make sure to select a consultant and your available time slot before booking for an appointment with our hospital.',
    instructionDoctor: 'Please select a date and time to see availability.',
    consultantList: 'Consultant List',
    selectDoctor: 'Select Doctor',
    dateLabel: 'Date',
    bookAppointment: 'Book Appointment',
    about: 'About',
    totalBeds: 'Total Beds:',
    phoneLabel: 'Phone:',
    emailLabel: 'Email:',
    // Doctor schedule
    selectDate: 'Select Date',
    availableTimeSlots: 'Available Time Slots',
    checkingSchedule: "Checking doctor's schedule...",
    noSlots: 'No slots available for this date.',
    noSlotsAvailable: 'No slots available for this date.',
    selectDateFirst: 'Select Date First',
    // Reviews (static samples)
    reviewTitleHospital: 'Great Service',
    reviewBodyHospital: 'Excellent healthcare facility with caring staff.',
    reviewTitleDoctor: 'Excellent Doctor',
    reviewBodyDoctor: 'Very professional and caring physician.',
    patientLabel: 'Patient',
    reviewDateSample: 'Dec 2024',
    // Profile placeholders / messages
    phone: 'Phone',
    address: 'Address',
    profileLocked: 'Your profile is locked. You cannot edit.',
    profileUpdated: 'Profile updated successfully',
    profileLoadFailed: 'Failed to load profile',
    // Documents
    verified: 'Verified',
    delete: 'Delete',
    docsLoadFailed: 'Failed to load documents',
    docUploaded: 'Document uploaded',
    uploadFailed: 'Upload failed',
    deleteFailed: 'Delete failed',
    // Doctor / availability labels
    available: 'Available',
    busy: 'Busy',
    onLeave: 'On Leave',
    appointmentType: 'Appointment Type',
    inPersonVisit: 'In-Person Visit',
    onlineVideoCall: 'Online Video Call',
    licenseLabel: 'License:',
    hospitalLabel: 'Hospital:',
    // Additional UI labels
    welcomeMessage: 'Welcome to HealthConnect!',
    loggedInAs: 'Successfully logged in as',
    yourProfile: 'Your Profile',
    quickLinks: 'Quick Links',
    onlineAppointments: 'Online Appointments',
    icu: 'ICU',
    generalBed: 'General Bed',
    cabin: 'Cabin',
    // Dashboard descriptions
    manageOnlineConsultations: 'Manage online consultations',
    setYourSchedule: 'Set your schedule',
    searchMedicalFacilities: 'Search medical facilities',
    findHealthcareProviders: 'Find healthcare providers',
    viewYourBookings: 'View your bookings',
    manageYourFiles: 'Manage your files',
    savedDoctorsHospitals: 'Saved doctors & hospitals',
    rateReviewServices: 'Rate and review services',
    yourAlertsMessages: 'Your alerts and messages',
    labTestsResults: 'Lab tests and results',
    signOutAccount: 'Sign out of your account',
    // ICU Booking page
    icuBedBooking: 'ICU Bed Booking',
    findBookICUBeds: 'Find and book ICU beds across hospitals in Dhaka',
    filterByLocation: 'Filter by Location',
    allLocations: 'All Locations',
    searchHospital: 'Search Hospital',
    enterHospitalName: 'Enter hospital name...',
    search: 'Search',
    loadingICUData: 'Loading ICU data...',
    noICUDataAvailable: 'No ICU data available',
    icuAvailable: 'Available',
    icuBooked: 'Booked',
    icuTotal: 'Total',
    pricePerDay: 'Price/Day:',
    bookICU: 'Book ICU',
    joinWaitlist: 'Join Waitlist',
    checkInDate: 'Check-in Date *',
    patientName: 'Patient Name *',
    phoneNumber: 'Phone Number *',
    notesOptional: 'Notes (Optional)',
    anySpecialRequirements: 'Any special requirements...',
    cancelButton: 'Cancel',
    confirmBooking: 'Confirm Booking',
    bookingProcess: 'Booking...',
    joinWaitlistAt: 'Join Waitlist at',
    noICUBedsAvailable: 'No ICU beds are currently available. Join the waitlist and we\'ll notify you when a bed becomes available.',
    emailAddress: 'Email Address *',
    nameOptional: 'Name (Optional)',
    enterYourName: 'Enter your name',
    phoneOptional: 'Phone (Optional)',
    enterPhoneNumber: 'Enter phone number',
    joining: 'Joining...',
    icuBookingConfirmed: 'Booking Confirmed!',
    yourICUBedBooked: 'Your ICU bed has been successfully booked.',
    bookingID: 'Booking ID:',
    hospital: 'Hospital:',
    checkInDateLabel: 'Check-in Date:',
    patientDisplay: 'Patient:',
    phoneDisplay: 'Phone:',
    confirmationEmailSent: 'A confirmation email has been sent to your registered email address.',
    done: 'Done',
    // General Bed Booking page
    generalBedBooking: 'General Bed Booking',
    findBookGeneralBeds: 'Find and book General Beds across hospitals in Dhaka',
    loadingGeneralBedData: 'Loading General Bed data...',
    noGeneralBedDataAvailable: 'No General Bed data available',
    bookBed: 'Book Bed',
    generalBedBookingConfirmed: 'Booking Confirmed!',
    yourGeneralBedBooked: 'Your General Bed has been successfully booked.',
    // Cabin Booking page
    cabinBooking: 'Cabin Booking',
    findBookCabins: 'Find and book Cabins across hospitals in Dhaka',
    loadingCabinData: 'Loading Cabin data...',
    noCabinDataAvailable: 'No Cabin data available',
    bookCabin: 'Book Cabin',
    cabinBookingConfirmed: 'Booking Confirmed!',
    yourCabinBooked: 'Your Cabin has been successfully booked.',
    // Additional keys used across pages

    when: 'When',
    type: 'Type',
    inPerson: 'In-person',
    online: 'Online',
    doctorIdPlaceholder: 'Doctor ID',
    notAvailable: 'N/A',
    waitlisted: 'Waitlisted',
    booked: 'Booked',
    approved: 'Approved',
    cancelled: 'Cancelled',
    completed: 'Completed',
    failedToLoadReviews: 'Failed to load reviews',
    reviewSubmitted: 'Review submitted',
    failedToSubmitReview: 'Failed to submit review',
    reviews: 'Reviews',
    targetIdPlaceholder: 'Target ID (doctor/hospital)',
    commentPlaceholder: 'Write your comment...',
    submitReview: 'Submit Review',
    rating: 'Rating',
    // Favorites
    myFavorites: 'My Favorites',
    filterBy: 'Filter by',
    all: 'All',
    noFavoritesFound: 'No favorites found',
    addFavoritesHint: 'Add doctors and hospitals to your favorites to see them here',
    removeFromFavorites: 'Remove from favorites',
    favoriteRemoved: 'Favorite removed successfully',
    failedToRemoveFavorite: 'Failed to remove favorite',
    failedToLoadFavorites: 'Failed to load favorites',
    specialty: 'Specialty',
    consultationFee: 'Consultation Fee',
    viewProfile: 'View Profile',
    addedOn: 'Added on',
    // Notifications
    notifications: 'Notifications',
    emailSent: 'Email sent successfully',
    emailFailed: 'Failed to send email',
    smsSent: 'SMS sent successfully',
    smsFailed: 'Failed to send SMS',
    appointmentReminder: 'Appointment Reminder',
    bookingConfirmed: 'Booking Confirmed',
    statusUpdated: 'Status Updated',
    otpSent: 'OTP sent successfully',
    // Accessibility
    skipToContent: 'Skip to main content',
    mainNavigation: 'Main navigation',
    searchLabel: 'Search',
    closeMenu: 'Close menu',
    openMenu: 'Open menu',
    // Reviews additional
    writeReview: 'Write a Review',
    reviewTarget: 'Review Target',
    appointmentId: 'Appointment ID',
    appointmentIdPlaceholder: 'Enter appointment ID',
    comment: 'Comment',
    allReviews: 'All Reviews',
    myReviews: 'My Reviews',
    pendingReviews: 'Pending Reviews',
    noReviewsFound: 'No reviews found',
    noMyReviewsFound: 'No reviews found',
    noPendingReviewsFound: 'No pending reviews found',
    approve: 'Approve',
    reject: 'Reject',
    fillAllFields: 'Please fill all required fields',
    reviewApproved: 'Review approved successfully',
    reviewRejected: 'Review rejected successfully',
    reviewDeleted: 'Review deleted successfully',
    failedToApproveReview: 'Failed to approve review',
    failedToRejectReview: 'Failed to reject review',
    failedToDeleteReview: 'Failed to delete review',
    confirmRejectReview: 'Are you sure you want to reject this review?',
    confirmDeleteReview: 'Are you sure you want to delete this review?',
    appointment: 'Appointment',
    pending: 'Pending',
    // Notifications additional
    markAllAsRead: 'Mark all as read',
    unread: 'unread',
    noNotificationsFound: 'No notifications found',
    markAsRead: 'Mark as read',
    deleteNotification: 'Delete notification',
    failedToLoadNotifications: 'Failed to load notifications',
    // Lab Orders
    labOrdersDoctor: 'Lab Orders (Doctor)',
    labOrdersLab: 'Lab Orders (Lab)',
    myLabOrders: 'My Lab Orders',
    createNewLabOrder: 'Create New Lab Order',
    patientId: 'Patient ID',
    patientIdPlaceholder: 'Enter patient user ID',
    testName: 'Test Name',
    testNamePlaceholder: 'e.g., CBC, X-Ray, Blood Sugar',
    notes: 'Notes',
    notesPlaceholder: 'Additional instructions or notes',
    createLabOrder: 'Create Lab Order',
    loadingLabOrders: 'Loading lab orders...',
    noLabOrdersFound: 'No lab orders found',
    createdOn: 'Created on',
    result: 'Result',
    viewResult: 'View Result',
    uploadPatientResult: 'Upload Patient Result',
    uploadLabResult: 'Upload Lab Result',
    uploading: 'Uploading...',
    updateLabOrder: 'Update Lab Order',
    updateStatus: 'Update Status',
    inProgress: 'In Progress',
    ordered: 'Ordered',
    failedToLoadLabOrders: 'Failed to load lab orders',
    fillAllRequiredFields: 'Please fill all required fields',
    labOrderCreated: 'Lab order created successfully',
    failedToCreateLabOrder: 'Failed to create lab order',
    enterNewStatus: 'Enter new status',
    enterResultUrl: 'Enter result URL (optional)',
    labOrderUpdated: 'Lab order updated successfully',
    failedToUpdateLabOrder: 'Failed to update lab order',
    resultUploaded: 'Result uploaded successfully',
    failedToUploadResult: 'Failed to upload result',
    labStatusUpdated: 'Lab status updated successfully',
    failedToUpdateStatus: 'Failed to update status',
    labResultUploaded: 'Lab result uploaded successfully',
    failedToUploadLabResult: 'Failed to upload lab result',
    toggleLanguage: 'Toggle language',
    confirmPassword: 'Confirm Password',
    male: 'Male',
    female: 'Female',
    other: 'Other',
    selectGender: 'Select Gender',
    // Navigation
    readTerms: 'Read our T&Cs',
    creatingAccount: 'Creating Account...',
    createAccount: 'Create an Account',
  },
  bn: {
    appName: 'হেলথকনেক্ট',
    icu: 'আইসিইউ',
    generalBed: 'জেনারেল বেড',
    cabin: 'কেবিন',
    hospitals: 'হাসপাতাল',
    doctors: 'ডাক্তার',
    appointments: 'অ্যাপয়েন্টমেন্ট',
    ambulance: 'অ্যাম্বুলেন্স',
    locations: 'লোকেশন',
    booking: 'বুকিং',
    contact: 'যোগাযোগ',
    link: 'লিংক',
    dashboard: 'ড্যাশবোর্ড',
    signIn: 'সাইন ইন',
    register: 'রেজিস্টার',
    findHospitals: 'হাসপাতাল খুঁজুন',
    findDoctor: 'ডাক্তার খুঁজুন',
    latestReviews: 'সর্বশেষ রিভিউ',
    newsletterTitle: 'সর্বশেষ আপডেট পেতে',
    newsletterSubtitle: 'আমাদের দৈনিক নিউজলেটারে যোগ দিন',
    newsletterPlaceholder: 'আপনি@example.com',
    submit: 'সাবমিট',
    logout: 'লগআউট',
    loading: 'লোড হচ্ছে...',
    accessDenied: 'অ্যাক্সেস অনুমোদিত নয়',
    // Auth / common
    email: 'ইমেইল',
    password: 'পাসওয়ার্ড',
    login: 'লগ ইন',
    verification: 'যাচাইকরণ',
    dontHaveAccount: 'একটি অ্যাকাউন্ট নেই?',
    haveAccount: 'ইতিমধ্যে একটি অ্যাকাউন্ট আছে?',
    createAccount: 'অ্যাকাউন্ট তৈরি করুন',
    forgotPassword: 'পাসওয়ার্ড ভুলে গেছেন?',
    backToLogin: 'লগইনে ফিরে যান',
    otpSentTo: 'আমরা কোড পাঠিয়েছি',
    enterCode: '৬-সংখ্যার কোড লিখুন',
    processing: 'প্রসেসিং হচ্ছে...',
    verifyCode: 'কোড যাচাই করুন',
    registration: 'রেজিস্ট্রেশন',
    name: 'নাম',
    gender: 'লিঙ্গ',
    dateOfBirth: 'জন্ম তারিখ',
    registerAs: 'রেজিস্টার করুন',
    patient: 'রোগী',
    doctor: 'ডাক্তার',
    admin: 'অ্যাডমিন',
    acceptTerms: 'আমি শর্তাবলীতে সম্মত',
    myProfile: 'আমার প্রোফাইল',
    myDocuments: 'আমার ডকুমেন্ট',
    myAppointments: 'আমার অ্যাপয়েন্টমেন্ট',
    adminDashboard: 'অ্যাডমিন ড্যাশবোর্ড',
    manageAvailability: 'আমার অ্যাভেইলেবিলিটি ম্যানেজ করুন',
    saveChanges: 'পরিবর্তন সংরক্ষণ করুন',
    save: 'সেভ',
    upload: 'আপলোড',
    book: 'বুক করুন',
    reschedule: 'রিশিডিউল',
    cancel: 'বাতিল',
    noRecordsFound: 'কোনো মেডিকেল রেকর্ড পাওয়া যায়নি',
    myMedicalRecords: 'আমার মেডিকেল রেকর্ড',
    // Search / details
    loadingHospitals: 'হাসপাতাল লোড হচ্ছে...',
    loadingDoctors: 'ডাক্তার লোড হচ্ছে...',
    noHospitals: 'কোনো হাসপাতাল পাওয়া যায়নি',
    noDoctors: 'কোনো ডাক্তার পাওয়া যায়নি',
    noDoctorsFound: 'কোনো ডাক্তার পাওয়া যায়নি',
    consultationLabel: 'পরামর্শ ফি',
    visitingFeeLabel: 'ভিজিটিং ফি',
    visitingFee: 'ভিজিটিং ফি',
    taka: 'টাকা',
    instructionHospital:
      'দয়া করে আমাদের হাসপাতালে অ্যাপয়েন্টমেন্ট বুক করার আগে একজন কনসালট্যান্ট এবং আপনার সুবিধাজনক সময় স্লট নির্বাচন করুন।',
    instructionDoctor: 'অনুগ্রহ করে তারিখ ও সময় নির্বাচন করে অ্যাভেইলেবিলিটি দেখুন।',
    consultantList: 'কনসালট্যান্ট তালিকা',
    selectDoctor: 'ডাক্তার নির্বাচন করুন',
    dateLabel: 'তারিখ',
    bookAppointment: 'অ্যাপয়েন্টমেন্ট বুক করুন',
    about: 'সম্বন্ধে',
    totalBeds: 'মোট বেড:',
    phoneLabel: 'ফোন:',
    emailLabel: 'ইমেইল:',
    // Doctor schedule
    selectDate: 'তারিখ নির্বাচন করুন',
    availableTimeSlots: 'উপলব্ধ সময় স্লট',
    checkingSchedule: 'ডাক্তারের সময়সূচি যাচাই করা হচ্ছে...',
    noSlots: 'এই তারিখে কোনো স্লট খালি নেই।',
    noSlotsAvailable: 'এই তারিখে কোনো স্লট খালি নেই।',
    selectDateFirst: 'আগে তারিখ নির্বাচন করুন',
    // Reviews (static samples)
    reviewTitleHospital: 'চমৎকার সেবা',
    reviewBodyHospital: 'দারুণ চিকিৎসা সেবা এবং যত্নশীল স্টাফ।',
    reviewTitleDoctor: 'দক্ষ ডাক্তার',
    reviewBodyDoctor: 'খুবই পেশাদার এবং যত্নশীল চিকিৎসা দেন।',
    patientLabel: 'রোগী',
    reviewDateSample: 'ডিসে ২০২৪',
    // Profile placeholders / messages
    phone: 'ফোন',
    address: 'ঠিকানা',
    profileLocked: 'আপনার প্রোফাইল লক করা হয়েছে। আপনি পরিবর্তন করতে পারবেন না।',
    profileUpdated: 'প্রোফাইল সফলভাবে আপডেট হয়েছে',
    profileLoadFailed: 'প্রোফাইল লোড করতে ব্যর্থ হয়েছে',
    // Documents
    verified: 'ভেরিফাইড',
    delete: 'ডিলিট',
    docsLoadFailed: 'ডকুমেন্ট লোড করতে ব্যর্থ হয়েছে',
    docUploaded: 'ডকুমেন্ট আপলোড হয়েছে',
    uploadFailed: 'আপলোড ব্যর্থ হয়েছে',
    deleteFailed: 'ডিলিট ব্যর্থ হয়েছে',
    // Doctor / availability labels
    available: 'উপলব্ধ',
    busy: 'ব্যস্ত',
    onLeave: 'ছুটিতে',
    appointmentType: 'অ্যাপয়েন্টমেন্টের ধরণ',
    inPersonVisit: 'সাক্ষাতে সাক্ষাৎকার',
    onlineVideoCall: 'অনলাইন ভিডিও কল',
    licenseLabel: 'লাইসেন্স:',
    hospitalLabel: 'হাসপাতাল:',
    // Additional UI labels
    welcomeMessage: 'হেলথকনেক্ট-এ স্বাগতম!',
    loggedInAs: 'সফলভাবে লগইন করেছেন',
    yourProfile: 'আপনার প্রোফাইল',
    quickLinks: 'কুইক লিংক',
    onlineAppointments: 'অনলাইন অ্যাপয়েন্টমেন্ট',
    icu: 'আইসিইউ',
    generalBed: 'জেনারেল বেড',
    cabin: 'কেবিন',
    // Dashboard descriptions
    manageOnlineConsultations: 'অনলাইন পরামর্শ পরিচালনা করুন',
    setYourSchedule: 'আপনার সময়সূচি নির্ধারণ করুন',
    searchMedicalFacilities: 'চিকিৎসা সুবিধা খুঁজুন',
    findHealthcareProviders: 'স্বাস্থ্যসেবা প্রদানকারী খুঁজুন',
    viewYourBookings: 'আপনার বুকিং দেখুন',
    manageYourFiles: 'আপনার ফাইলগুলি পরিচালনা করুন',
    savedDoctorsHospitals: 'সংরক্ষিত ডাক্তার ও হাসপাতাল',
    rateReviewServices: 'সেবা রেট ও রিভিউ করুন',
    yourAlertsMessages: 'আপনার সতর্কতা ও বার্তা',
    labTestsResults: 'ল্যাব টেস্ট ও ফলাফল',
    signOutAccount: 'আপনার অ্যাকাউন্ট থেকে সাইন আউট',
    // ICU Booking page
    icuBedBooking: 'আইসিইউ বেড বুকিং',
    findBookICUBeds: 'ঢাকার হাসপাতালগুলিতে আইসিইউ বেড খুঁজুন এবং বুক করুন',
    filterByLocation: 'লোকেশন অনুযায়ী ফিল্টার',
    allLocations: 'সব লোকেশন',
    searchHospital: 'হাসপাতাল খুঁজুন',
    enterHospitalName: 'হাসপাতালের নাম লিখুন...',
    search: 'খুঁজুন',
    loadingICUData: 'আইসিইউ ডেটা লোড হচ্ছে...',
    noICUDataAvailable: 'কোনো আইসিইউ ডেটা পাওয়া যায়নি',
    icuAvailable: 'উপলব্ধ',
    icuBooked: 'বুক করা',
    icuTotal: 'মোট',
    pricePerDay: 'দৈনিক মূল্য:',
    bookICU: 'আইসিইউ বুক করুন',
    joinWaitlist: 'ওয়েটলিস্টে যোগ দিন',
    checkInDate: 'চেক-ইন তারিখ *',
    patientName: 'রোগীর নাম *',
    phoneNumber: 'ফোন নম্বর *',
    notesOptional: 'নোট (ঐচ্ছিক)',
    anySpecialRequirements: 'কোনো বিশেষ প্রয়োজন...',
    cancelButton: 'বাতিল',
    confirmBooking: 'বুকিং নিশ্চিত করুন',
    bookingProcess: 'বুক করা হচ্ছে...',
    joinWaitlistAt: 'এ যোগ দিন',
    noICUBedsAvailable: 'বর্তমানে কোনো আইসিইউ বেড উপলব্ধ নেই। ওয়েটলিস্টে যোগ দিন এবং বেড পাওয়া গেলে আমরা আপনাকে জানাব।',
    emailAddress: 'ইমেইল ঠিকানা *',
    nameOptional: 'নাম (ঐচ্ছিক)',
    enterYourName: 'আপনার নাম লিখুন',
    phoneOptional: 'ফোন (ঐচ্ছিক)',
    enterPhoneNumber: 'ফোন নম্বর লিখুন',
    joining: 'যোগ দেওয়া হচ্ছে...',
    icuBookingConfirmed: 'বুকিং নিশ্চিত!',
    yourICUBedBooked: 'আপনার আইসিইউ বেড সফলভাবে বুক করা হয়েছে।',
    bookingID: 'বুকিং আইডি:',
    hospital: 'হাসপাতাল:',
    checkInDateLabel: 'চেক-ইন তারিখ:',
    patientDisplay: 'রোগী:',
    phoneDisplay: 'ফোন:',
    confirmationEmailSent: 'একটি নিশ্চিতকরণ ইমেইল আপনার নিবন্ধিত ইমেইল ঠিকানায় পাঠানো হয়েছে।',
    done: 'সম্পন্ন',
    // General Bed Booking page
    generalBedBooking: 'জেনারেল বেড বুকিং',
    findBookGeneralBeds: 'ঢাকার হাসপাতালগুলিতে জেনারেল বেড খুঁজুন এবং বুক করুন',
    loadingGeneralBedData: 'জেনারেল বেড ডেটা লোড হচ্ছে...',
    noGeneralBedDataAvailable: 'কোনো জেনারেল বেড ডেটা পাওয়া যায়নি',
    bookBed: 'বেড বুক করুন',
    generalBedBookingConfirmed: 'বুকিং নিশ্চিত!',
    yourGeneralBedBooked: 'আপনার জেনারেল বেড সফলভাবে বুক করা হয়েছে।',
    // Cabin Booking page
    cabinBooking: 'কেবিন বুকিং',
    findBookCabins: 'ঢাকার হাসপাতালগুলিতে কেবিন খুঁজুন এবং বুক করুন',
    loadingCabinData: 'কেবিন ডেটা লোড হচ্ছে...',
    noCabinDataAvailable: 'কোনো কেবিন ডেটা পাওয়া যায়নি',
    bookCabin: 'কেবিন বুক করুন',
    cabinBookingConfirmed: 'বুকিং নিশ্চিত!',
    yourCabinBooked: 'আপনার কেবিন সফলভাবে বুক করা হয়েছে।',
    // Additional keys used across pages (Bangla)
    when: 'কখন',
    type: 'ধরণ',
    inPerson: 'সাক্ষাৎকার',
    online: 'অনলাইন',
    doctorIdPlaceholder: 'ডাক্তার আইডি',
    notAvailable: 'প্রাপ্য নয়',
    waitlisted: 'ওয়েটলিস্টেড',
    booked: 'বুক করা হয়েছে',
    approved: 'মঞ্জুর করা হয়েছে',
    cancelled: 'বাতিল',
    completed: 'সম্পন্ন',
    failedToLoadReviews: 'রিভিউ লোড করতে ব্যর্থ',
    reviewSubmitted: 'রিভিউ সাবমিট হয়েছে',
    failedToSubmitReview: 'রিভিউ সাবমিট করতে ব্যর্থ',
    reviews: 'রিভিউ',
    targetIdPlaceholder: 'টার্গেট আইডি (ডাক্তার/হাসপাতাল)',
    commentPlaceholder: 'আপনার মন্তব্য লিখুন...',
    submitReview: 'রিভিউ সাবমিট করুন',
    rating: 'রেটিং',
    // Favorites
    myFavorites: 'আমার প্রিয়',
    filterBy: 'ফিল্টার করুন',
    all: 'সব',
    noFavoritesFound: 'কোনো প্রিয় পাওয়া যায়নি',
    addFavoritesHint: 'ডাক্তার ও হাসপাতালকে প্রিয় হিসেবে যোগ করুন',
    removeFromFavorites: 'প্রিয় থেকে সরান',
    favoriteRemoved: 'প্রিয় সফলভাবে সরানো হয়েছে',
    failedToRemoveFavorite: 'প্রিয় সরাতে ব্যর্থ',
    failedToLoadFavorites: 'প্রিয় লোড করতে ব্যর্থ',
    specialty: 'বিশেষত্ব',
    consultationFee: 'পরামর্শ ফি',
    viewProfile: 'প্রোফাইল দেখুন',
    addedOn: 'যোগ করা হয়েছে',
    // Notifications
    notifications: 'বিজ্ঞপ্তি',
    emailSent: 'ইমেইল সফলভাবে পাঠানো হয়েছে',
    emailFailed: 'ইমেইল পাঠাতে ব্যর্থ',
    smsSent: 'এসএমএস সফলভাবে পাঠানো হয়েছে',
    smsFailed: 'এসএমএস পাঠাতে ব্যর্থ',
    appointmentReminder: 'অ্যাপয়েন্টমেন্ট রিমাইন্ডার',
    bookingConfirmed: 'বুকিং নিশ্চিত',
    statusUpdated: 'স্ট্যাটাস আপডেট',
    otpSent: 'ওটিপি সফলভাবে পাঠানো হয়েছে',
    // Accessibility
    skipToContent: 'প্রধান কন্টেন্টে যান',
    mainNavigation: 'প্রধান নেভিগেশন',
    searchLabel: 'অনুসন্ধান',
    closeMenu: 'মেনু বন্ধ করুন',
    openMenu: 'মেনু খুলুন',
    // Reviews additional
    writeReview: 'রিভিউ লিখুন',
    reviewTarget: 'রিভিউ টার্গেট',
    appointmentId: 'অ্যাপয়েন্টমেন্ট আইডি',
    appointmentIdPlaceholder: 'অ্যাপয়েন্টমেন্ট আইডি লিখুন',
    comment: 'মন্তব্য',
    allReviews: 'সব রিভিউ',
    myReviews: 'আমার রিভিউ',
    pendingReviews: 'অমীমুদিস্ট রিভিউ',
    noReviewsFound: 'কোনো রিভিউ পাওয়া যায়নি',
    noMyReviewsFound: 'কোনো রিভিউ পাওয়া যায়নি',
    noPendingReviewsFound: 'কোনো অমীমুদিস্ট রিভিউ নেই',
    approve: 'মঞ্জুর',
    reject: 'প্রত্যাখ্যান',
    fillAllFields: 'সব প্রয়োজনীয় ক্ষেত্র পূরণ করুন',
    reviewApproved: 'রিভিউ সফলভাবে মঞ্জুর হয়েছে',
    reviewRejected: 'রিভিউ প্রত্যাখ্যান করা হয়েছে',
    reviewDeleted: 'রিভিউ সফলভাবে ডিলিট হয়েছে',
    failedToApproveReview: 'রিভিউ মঞ্জুর করতে ব্যর্থ',
    failedToRejectReview: 'রিভিউ প্রত্যাখ্যান করতে ব্যর্থ',
    failedToDeleteReview: 'রিভিউ ডিলিট করতে ব্যর্থ',
    confirmRejectReview: 'আপনি কি নিশ্চিত যে এই রিভিউ প্রত্যাখ্যান করতে চান?',
    confirmDeleteReview: 'আপনি কি নিশ্চিত যে এই রিভিউ ডিলিট করতে চান?',
    appointment: 'অ্যাপয়েন্টমেন্ট',
    pending: 'অমীমুদিস্ট',
    // Notifications additional
    markAllAsRead: 'সব পড়া হয়েছে হিসেবে চিহ্নিত করুন',
    unread: 'অপডিত',
    noNotificationsFound: 'কোনো বিজ্ঞপ্তি পাওয়া যায়নি',
    markAsRead: 'পড়া হয়েছে হিসেবে চিহ্নিত করুন',
    deleteNotification: 'বিজ্ঞপ্তি ডিলিট করুন',
    failedToLoadNotifications: 'বিজ্ঞপ্তি লোড করতে ব্যর্থ',
    // Lab Orders
    labOrdersDoctor: 'ল্যাব অর্ডার (ডাক্তার)',
    labOrdersLab: 'ল্যাব অর্ডার (ল্যাব)',
    myLabOrders: 'আমার ল্যাব অর্ডার',
    createNewLabOrder: 'নতুন ল্যাব অর্ডার তৈরি করুন',
    patientId: 'রোগীর আইডি',
    patientIdPlaceholder: 'রোগীর ইউজার আইডি লিখুন',
    testName: 'টেস্টের নাম',
    testNamePlaceholder: 'যেমন, সিবিসি, এক্স-রে, ব্লাড সুগার',
    notes: 'নোট',
    notesPlaceholder: 'অতিরিক্ত নির্দেশনা বা নোট',
    createLabOrder: 'ল্যাব অর্ডার তৈরি করুন',
    loadingLabOrders: 'ল্যাব অর্ডার লোড হচ্ছে...',
    noLabOrdersFound: 'কোনো ল্যাব অর্ডার পাওয়া যায়নি',
    createdOn: 'তৈরি করা হয়েছে',
    result: 'ফলাফল',
    viewResult: 'ফলাফল দেখুন',
    uploadPatientResult: 'রোগীর ফলাফল আপলোড করুন',
    uploadLabResult: 'ল্যাব ফলাফল আপলোড করুন',
    uploading: 'আপলোড হচ্ছে...',
    updateLabOrder: 'ল্যাব অর্ডার আপডেট করুন',
    updateStatus: 'স্ট্যাটাস আপডেট করুন',
    inProgress: 'চলমান',
    ordered: 'অর্ডার করা হয়েছে',
    failedToLoadLabOrders: 'ল্যাব অর্ডার লোড করতে ব্যর্থ',
    fillAllRequiredFields: 'সব প্রয়োজনীয় ক্ষেত্র পূরণ করুন',
    labOrderCreated: 'ল্যাব অর্ডার সফলভাবে তৈরি হয়েছে',
    failedToCreateLabOrder: 'ল্যাব অর্ডার তৈরি করতে ব্যর্থ',
    enterNewStatus: 'নতুন স্ট্যাটাস লিখুন',
    enterResultUrl: 'ফলাফলের URL লিখুন (ঐচ্ছিক)',
    labOrderUpdated: 'ল্যাব অর্ডার সফলভাবে আপডেট হয়েছে',
    failedToUpdateLabOrder: 'ল্যাব অর্ডার আপডেট করতে ব্যর্থ',
    resultUploaded: 'ফলাফল সফলভাবে আপলোড হয়েছে',
    failedToUploadResult: 'ফলাফল আপলোড করতে ব্যর্থ',
    labStatusUpdated: 'ল্যাব স্ট্যাটাস সফলভাবে আপডেট হয়েছে',
    failedToUpdateStatus: 'স্ট্যাটাস আপডেট করতে ব্যর্থ',
    labResultUploaded: 'ল্যাব ফলাফল সফলভাবে আপলোড হয়েছে',
    failedToUploadLabResult: 'ল্যাব ফলাফল আপলোড করতে ব্যর্থ',
    toggleLanguage: 'ভাষা পরিবর্তন করুন',
    confirmPassword: 'পাসওয়ার্ড নিশ্চিত করুন',
    male: 'পুরুষ',
    female: 'মহিলা',
    other: 'অন্য',
    selectGender: 'লিঙ্গ নির্বাচন করুন',
    // Navigation
    readTerms: 'আমাদের নিয়ম ও শর্তাবলী পড়ুন',
    creatingAccount: 'অ্যাকাউন্ট তৈরি হচ্ছে...',
  },
};

const LanguageContext = createContext(null);

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(
    localStorage.getItem('language') || 'en'
  );

  useEffect(() => {
    localStorage.setItem('language', language);
    // Basic accessibility: set document language attribute
    if (typeof document !== 'undefined') {
      document.documentElement.lang = language === 'bn' ? 'bn' : 'en';
    }
  }, [language]);

  const toggleLanguage = () => {
    setLanguage((prev) => (prev === 'en' ? 'bn' : 'en'));
  };

  const t = (key) => translations[language][key] || key;

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};


